### ISSUE TITLE
마우스포인트...이슈

### ISSUE THREAD

**Issue by DongYeolShin** [PureOpenSource/pureCanvas#1]
올려주신 소스를 잘 사용하고 있습니다.
브라우저의 크기에 따라서 찍히는 위치가 달라지는데....
해상도나  브라우저 크기와 상관없이  같은 위치에 찍히게하려면 어떻게해야할까요....

**Comment by PureJY** [comment]
배경이미지 크기에 따라 비율이 계산되어서 컨버스 크기가 달라도 같은 위치에 표시됩니다.
